// R68 (slice 17): the reviewed table of every route's guard, read from the decorators of the real
// AppModule by test/core/routes.e2e-spec.ts. A route added, removed or re-guarded fails that test
// until this table is edited, so a changed guard is a visible diff in review, never a silent one:
// a capability list widened, a capacity swapped, a webhook provider or a platform level changed.
//
// Format: 'METHOD path': 'decorator[: argument]'. @RequireCapability lists its capabilities in
// declared order, ANY of which admits (contracts/slice-2.md §1); the row scope of a capability
// route is computed per request (R53, R79) and is not a decorator argument. @RequireCapacity names
// the capacity, @Webhook the provider, @PlatformSession the level. Print the actual table with
// PRINT_ROUTE_GUARDS=1 when editing; never paste it unread.

export const ROUTE_GUARDS: Record<string, string> = {
  'GET /api/v1/academic-years': 'staff',
  'POST /api/v1/academic-years': 'capability: academic_year.manage',
  'GET /api/v1/academic-years/:id': 'staff',
  'PATCH /api/v1/academic-years/:id': 'capability: academic_year.manage',
  'POST /api/v1/academic-years/:id/activate': 'capability: academic_year.manage',
  'POST /api/v1/academic-years/:id/close': 'capability: academic_year.manage',
  'GET /api/v1/academic-years/:id/result-settings': 'staff',
  'PATCH /api/v1/academic-years/:id/result-settings': 'capability: assessment.define',
  'GET /api/v1/academic-years/:id/terms': 'staff',
  'POST /api/v1/academic-years/:id/terms': 'capability: assessment.define',
  'POST /api/v1/admissions': 'capability: student.create',
  'GET /api/v1/announcements': 'capability: announcement.send.school | announcement.send.scope',
  'POST /api/v1/announcements': 'capability: announcement.send.school | announcement.send.scope',
  'GET /api/v1/announcements/:id': 'capability: announcement.send.school | announcement.send.scope',
  'PATCH /api/v1/announcements/:id': 'capability: announcement.send.school | announcement.send.scope',
  'GET /api/v1/announcements/:id/attachment': 'capability: announcement.send.school | announcement.send.scope',
  'POST /api/v1/announcements/:id/cancel': 'capability: announcement.send.school | announcement.send.scope',
  'GET /api/v1/announcements/:id/delivery': 'capability: announcement.send.school | announcement.send.scope',
  'POST /api/v1/announcements/:id/send': 'capability: announcement.send.school | announcement.send.scope',
  'GET /api/v1/announcements/:id/thumbnail': 'capability: announcement.send.school | announcement.send.scope',
  'POST /api/v1/announcements/preview-audience': 'capability: announcement.send.school | announcement.send.scope',
  // Phase 4 slice 30 (contracts/slice-30.md §1): reads with either marks key, writes with
  // marks.enter (the row scope is the subject-aware MarksScope of held_on, per request).
  'GET /api/v1/assessments': 'capability: marks.enter | marks.view_all',
  'POST /api/v1/assessments': 'capability: marks.enter',
  'GET /api/v1/assessments/:id': 'capability: marks.enter | marks.view_all',
  'PATCH /api/v1/assessments/:id': 'capability: marks.enter | assessment.define',
  'GET /api/v1/assessments/:id/marks': 'capability: marks.enter | marks.view_all',
  'POST /api/v1/assessments/:id/submit-marks': 'capability: marks.enter',
  'POST /api/v1/assessments/:id/void': 'capability: marks.enter | assessment.define',
  'POST /api/v1/attendance-arrivals': 'capability: attendance.student.mark',
  'POST /api/v1/attendance-marks/:id/amend': 'capability: attendance.student.mark',
  'GET /api/v1/attendance-marks/:id/changes': 'capability: attendance.student.mark | attendance.student.view_all',
  'GET /api/v1/attendance-registers': 'capability: attendance.student.view_all | attendance.student.mark',
  'GET /api/v1/attendance-reports/absentees': 'capability: attendance.student.view_all',
  'GET /api/v1/attendance-reports/daily-summary': 'capability: attendance.student.view_all | attendance.student.mark',
  'GET /api/v1/attendance-reports/late': 'capability: attendance.student.view_all',
  'GET /api/v1/attendance-reports/percentage': 'capability: attendance.student.view_all',
  'POST /api/v1/auth/forgot-password': 'public',
  'POST /api/v1/auth/login': 'public',
  'POST /api/v1/auth/logout': 'authenticated-only',
  'POST /api/v1/auth/reset-password': 'public',
  'POST /api/v1/auth/verify-email': 'public',
  'GET /api/v1/calendar/teaching-days': 'staff',
  'GET /api/v1/classes': 'staff',
  'POST /api/v1/classes': 'capability: class.manage',
  'GET /api/v1/classes/:id': 'staff',
  'PATCH /api/v1/classes/:id': 'capability: class.manage',
  'POST /api/v1/classes/:id/archive': 'capability: class.manage',
  'POST /api/v1/classes/:id/copy-sections': 'capability: class.manage',
  'GET /api/v1/classes/:id/sections': 'staff',
  'POST /api/v1/classes/:id/sections': 'capability: section.manage',
  'GET /api/v1/classes/:id/subjects': 'staff',
  'GET /api/v1/custom-roles': 'capability: user.account.manage | role.manage',
  'POST /api/v1/custom-roles': 'capability: role.manage',
  'GET /api/v1/custom-roles/:id': 'capability: user.account.manage | role.manage',
  'PATCH /api/v1/custom-roles/:id': 'capability: role.manage',
  'POST /api/v1/custom-roles/:id/archive': 'capability: role.manage',
  'GET /api/v1/diary-entries/:id': 'capability: diary.write',
  'PATCH /api/v1/diary-entries/:id': 'capability: diary.write',
  'GET /api/v1/diary-entries/:id/attachment': 'capability: diary.write',
  'GET /api/v1/diary-entries/:id/thumbnail': 'capability: diary.write',
  'GET /api/v1/documents/:id/content': 'capability: document.view',
  'PATCH /api/v1/enrolments/:id': 'capability: enrolment.manage',
  'POST /api/v1/enrolments/:id/change-class': 'capability: enrolment.manage',
  'POST /api/v1/enrolments/:id/change-section': 'capability: enrolment.manage',
  'POST /api/v1/grants/:id/end': 'capability: role.manage',
  'PATCH /api/v1/guardian-links/:id': 'capability: guardian.manage',
  'POST /api/v1/guardian-links/:id/end': 'capability: guardian.manage',
  'GET /api/v1/guardians': 'capability: guardian.manage',
  'POST /api/v1/guardians': 'capability: guardian.manage',
  'GET /api/v1/guardians/:id': 'capability: guardian.manage',
  'PATCH /api/v1/guardians/:id': 'capability: guardian.manage',
  'POST /api/v1/guardians/:id/issue-login': 'capability: user.account.manage',
  'GET /api/v1/guardians/:id/students': 'capability: guardian.manage',
  'POST /api/v1/guardians/lookup': 'capability: student.create | guardian.manage',
  'GET /api/v1/health': 'public',
  'GET /api/v1/holidays': 'staff',
  'POST /api/v1/holidays': 'capability: holiday.manage',
  'GET /api/v1/holidays/:id': 'staff',
  'PATCH /api/v1/holidays/:id': 'capability: holiday.manage',
  'POST /api/v1/holidays/:id/cancel': 'capability: holiday.manage',
  'POST /api/v1/holidays/:id/publish': 'capability: holiday.manage',
  'GET /api/v1/me': 'authenticated-only',
  // Phase 3 slice 27: the Approvals tab and page; each section is present only for its key (R227).
  'GET /api/v1/me/approvals': 'staff',
  'GET /api/v1/me/calendar': 'authenticated-only',
  'POST /api/v1/me/change-email': 'authenticated-only',
  'POST /api/v1/me/change-password': 'authenticated-only',
  'GET /api/v1/me/children/:id/attendance': 'capacity: guardian',
  'GET /api/v1/me/children/:id/diary-entries': 'capacity: guardian',
  'GET /api/v1/me/children/:id/diary-entries/:entryId/attachment': 'capacity: guardian',
  'GET /api/v1/me/children/:id/diary-entries/:entryId/thumbnail': 'capacity: guardian',
  'GET /api/v1/me/children/:id/remarks': 'capacity: guardian',
  'POST /api/v1/me/devices': 'authenticated-only',
  'GET /api/v1/me/inbox': 'authenticated-only',
  'GET /api/v1/me/inbox/:id': 'authenticated-only',
  'GET /api/v1/me/inbox/:id/attachment': 'authenticated-only',
  'GET /api/v1/me/inbox/:id/thumbnail': 'authenticated-only',
  'POST /api/v1/me/sessions/revoke-others': 'authenticated-only',
  'GET /api/v1/me/staff/attendance': 'staff',
  // Phase 3 slice 24: a staff member's own leave (staff id from the session).
  'GET /api/v1/me/staff/leave-balance': 'staff',
  'GET /api/v1/me/staff/leave-requests': 'staff',
  'POST /api/v1/me/staff/leave-requests': 'staff',
  'GET /api/v1/me/staff/leave-requests/:id': 'staff',
  'POST /api/v1/me/staff/leave-requests/:id/cancel': 'staff',
  // Phase 3 slice 25: a staff member's own salary and payslips (staff id from the session, R217).
  'GET /api/v1/me/staff/salary-structure': 'staff',
  'GET /api/v1/me/staff/payslips': 'staff',
  'GET /api/v1/me/staff/payslips/:id': 'staff',
  'GET /api/v1/me/staff/payslips/:id/print': 'staff',
  'GET /api/v1/me/student/attendance': 'capacity: student',
  'GET /api/v1/me/student/diary-entries': 'capacity: student',
  'GET /api/v1/me/student/diary-entries/:entryId/attachment': 'capacity: student',
  'GET /api/v1/me/student/diary-entries/:entryId/thumbnail': 'capacity: student',
  'GET /api/v1/me/student/remarks': 'capacity: student',
  'POST /api/v1/messaging/test': 'capability: school.settings.manage',
  'GET /api/v1/messaging/usage': 'capability: school.settings.manage',
  'GET /api/v1/messaging/whatsapp': 'capability: school.settings.manage',
  'POST /api/v1/messaging/whatsapp/connect-cloud-api': 'capability: school.settings.manage',
  'POST /api/v1/messaging/whatsapp/disable': 'capability: school.settings.manage',
  'POST /api/v1/messaging/whatsapp/pair': 'capability: school.settings.manage',
  'POST /api/v1/platform/auth/change-password': 'platform-session: password-change',
  'POST /api/v1/platform/auth/login': 'public',
  'POST /api/v1/platform/auth/logout': 'platform-session: any',
  'POST /api/v1/platform/auth/totp/confirm': 'platform-session: any',
  'POST /api/v1/platform/auth/totp/enrol': 'platform-session: any',
  'GET /api/v1/platform/me': 'platform-session: any',
  'GET /api/v1/platform/messaging/health': 'platform-session: full',
  // Phase 3 slice 26: platform billing (plans, invoices, a school's plan and cap).
  'GET /api/v1/platform/plans': 'platform-session: full',
  'POST /api/v1/platform/plans': 'platform-session: full',
  'GET /api/v1/platform/plans/:id': 'platform-session: full',
  'PATCH /api/v1/platform/plans/:id': 'platform-session: full',
  'POST /api/v1/platform/plans/:id/archive': 'platform-session: full',
  'GET /api/v1/platform/invoices': 'platform-session: full',
  'POST /api/v1/platform/invoices/issue-month': 'platform-session: full',
  'GET /api/v1/platform/invoices/:id': 'platform-session: full',
  'POST /api/v1/platform/invoices/:id/record-payment': 'platform-session: full',
  'POST /api/v1/platform/invoices/:id/void': 'platform-session: full',
  'POST /api/v1/platform/schools/:id/assign-plan': 'platform-session: full',
  'GET /api/v1/platform/schools/:id/billing': 'platform-session: full',
  'POST /api/v1/platform/schools/:id/unpin-plan': 'platform-session: full',
  'POST /api/v1/platform/schools/:id/use-plan-allowance': 'platform-session: full',
  'GET /api/v1/platform/schools': 'platform-session: full',
  'POST /api/v1/platform/schools': 'platform-session: full',
  'GET /api/v1/platform/schools/:id': 'platform-session: full',
  'PATCH /api/v1/platform/schools/:id': 'platform-session: full',
  'POST /api/v1/platform/schools/:id/change-status': 'platform-session: full',
  'POST /api/v1/platform/schools/:id/issue-principal-login': 'platform-session: full',
  'GET /api/v1/platform/settings': 'platform-session: full',
  'PATCH /api/v1/platform/settings': 'platform-session: full',
  'POST /api/v1/remarks/:id/correct': 'capability: remark.write',
  // Phase 3 slice 18: finance readers (phase-3-financial.md §3.1, R234) and the setup writers.
  'GET /api/v1/fee-heads': 'capability: fee_head.manage | charge.create | fee.statement.view | payment.record',
  'POST /api/v1/fee-heads': 'capability: fee_head.manage',
  'GET /api/v1/fee-heads/:id': 'capability: fee_head.manage | charge.create | fee.statement.view | payment.record',
  'PATCH /api/v1/fee-heads/:id': 'capability: fee_head.manage',
  'POST /api/v1/fee-heads/:id/archive': 'capability: fee_head.manage',
  'GET /api/v1/fee-structures': 'capability: fee_head.manage | charge.create | fee.statement.view | payment.record',
  'POST /api/v1/fee-structures': 'capability: fee_head.manage',
  'POST /api/v1/fee-structures/copy': 'capability: fee_head.manage',
  'GET /api/v1/me/payment-accounts': 'capacity: guardian',
  'GET /api/v1/payment-accounts': 'capability: fee_head.manage | charge.create | fee.statement.view | payment.record',
  'POST /api/v1/payment-accounts': 'capability: school.settings.manage',
  'GET /api/v1/payment-accounts/:id': 'capability: fee_head.manage | charge.create | fee.statement.view | payment.record',
  'POST /api/v1/payment-accounts/:id/disable': 'capability: school.settings.manage',
  // Phase 3 slice 19 (contracts/slice-19.md §1): charges, runs, concessions, campaigns, statement.
  'GET /api/v1/charges': 'capability: fee.statement.view | charge.create',
  'POST /api/v1/charges': 'capability: charge.create',
  'POST /api/v1/charges/generate-month': 'capability: charge.create',
  'GET /api/v1/charges/generation-runs': 'capability: charge.create | finance.report.view',
  'GET /api/v1/charges/generation-runs/:id': 'capability: charge.create | finance.report.view',
  'GET /api/v1/charges/:id': 'capability: fee.statement.view | charge.create',
  'POST /api/v1/charges/:id/void': 'capability: charge.create | concession.grant',
  'POST /api/v1/charges/:id/waive': 'capability: concession.grant',
  'POST /api/v1/charges/:id/adjust': 'capability: concession.grant',
  'GET /api/v1/students/:id/fee-statement': 'capability: fee.statement.view',
  'GET /api/v1/concessions': 'capability: concession.grant | charge.create',
  'POST /api/v1/concessions': 'capability: charge.create',
  'GET /api/v1/concessions/:id': 'capability: concession.grant | charge.create',
  'POST /api/v1/concessions/:id/approve': 'capability: concession.grant',
  'POST /api/v1/concessions/:id/reject': 'capability: concession.grant',
  'POST /api/v1/concessions/:id/end': 'capability: concession.grant',
  'GET /api/v1/charge-campaigns': 'capability: charge.campaign.send',
  'POST /api/v1/charge-campaigns': 'capability: charge.campaign.send',
  'POST /api/v1/charge-campaigns/preview-targets': 'capability: charge.campaign.send',
  'GET /api/v1/charge-campaigns/:id': 'capability: charge.campaign.send',
  'PATCH /api/v1/charge-campaigns/:id': 'capability: charge.campaign.send',
  'POST /api/v1/charge-campaigns/:id/generate': 'capability: charge.campaign.send',
  'POST /api/v1/charge-campaigns/:id/cancel': 'capability: charge.campaign.send',
  // Phase 3 slice 20 (contracts/slice-20.md §1): the counter, payments, receipts, reversals,
  // custody and handovers. Refunds, refund reversals and shortfall resolution also need the
  // principal role (in the service, R233).
  'GET /api/v1/guardians/:id/dues': 'capability: payment.record | fee.statement.view',
  'POST /api/v1/payments/preview': 'capability: payment.record',
  'POST /api/v1/payments': 'capability: payment.record',
  'GET /api/v1/payments': 'capability: payment.record | fee.statement.view',
  'GET /api/v1/payments/:id': 'capability: payment.record | fee.statement.view',
  'POST /api/v1/payments/:id/void': 'capability: payment.void',
  'POST /api/v1/payments/:id/refund': 'capability: payment.void',
  'POST /api/v1/payments/:id/reverse-refund': 'capability: payment.void',
  'POST /api/v1/payments/:id/carry-forward': 'capability: payment.record',
  'POST /api/v1/payments/:id/carry-forward/undo': 'capability: payment.record',
  'GET /api/v1/receipts/:id': 'capability: payment.record | fee.statement.view',
  'GET /api/v1/receipts/:id/print': 'capability: payment.record | fee.statement.view',
  'GET /api/v1/me/staff/custody': 'staff',
  'GET /api/v1/me/staff/cash-handovers': 'staff',
  'POST /api/v1/me/staff/cash-handovers': 'capability: payment.record',
  'POST /api/v1/cash-handovers': 'capability: collection.handover.confirm',
  'GET /api/v1/cash-handovers': 'capability: collection.handover.confirm',
  'GET /api/v1/cash-handovers/:id': 'capability: collection.handover.confirm',
  'GET /api/v1/cash-handovers/:id/payments': 'capability: collection.handover.confirm',
  'POST /api/v1/cash-handovers/:id/confirm': 'capability: collection.handover.confirm',
  'POST /api/v1/cash-handovers/:id/resolve-shortfall': 'capability: collection.handover.confirm',
  // Phase 3 slice 21 (contracts/slice-21.md §1): the office's claim queue (payment.verify); the
  // guardian's dues, receipts, deposit claims and upload, all under /me (R78, R198).
  'GET /api/v1/payment-claims': 'capability: payment.verify',
  'GET /api/v1/payment-claims/:id': 'capability: payment.verify',
  'GET /api/v1/payment-claims/:id/image': 'capability: payment.verify',
  'GET /api/v1/payment-claims/:id/thumbnail': 'capability: payment.verify',
  'POST /api/v1/payment-claims/:id/verify': 'capability: payment.verify',
  'POST /api/v1/payment-claims/:id/reject': 'capability: payment.verify',
  'GET /api/v1/me/children/:id/dues': 'capacity: guardian',
  'GET /api/v1/me/children/:id/payment-claims': 'capacity: guardian',
  'POST /api/v1/me/children/:id/payment-claims': 'capacity: guardian',
  'GET /api/v1/me/children/:id/payment-claims/:claimId': 'capacity: guardian',
  'PATCH /api/v1/me/children/:id/payment-claims/:claimId': 'capacity: guardian',
  'POST /api/v1/me/children/:id/payment-claims/:claimId/withdraw': 'capacity: guardian',
  'GET /api/v1/me/children/:id/payment-claims/:claimId/image': 'capacity: guardian',
  'GET /api/v1/me/children/:id/payment-claims/:claimId/thumbnail': 'capacity: guardian',
  'GET /api/v1/me/receipts': 'capacity: guardian',
  'GET /api/v1/me/receipts/:id': 'capacity: guardian',
  'POST /api/v1/me/uploads': 'capacity: guardian',
  // Phase 3 slice 22 (contracts/slice-22.md §1): the finance reports, the reminders on demand and
  // the dues clearance; the override also needs the principal role (in the service, R233).
  'GET /api/v1/finance-reports/defaulters': 'capability: finance.report.view',
  'GET /api/v1/finance-reports/collections': 'capability: finance.report.view',
  'GET /api/v1/finance-reports/outstanding': 'capability: finance.report.view',
  'GET /api/v1/finance-reports/daily-cash': 'capability: finance.report.view',
  'GET /api/v1/finance-reports/concessions': 'capability: finance.report.view',
  'GET /api/v1/finance-reports/expenses': 'capability: finance.report.view',
  'GET /api/v1/finance-reports/payroll': 'capability: finance.report.view',
  'POST /api/v1/fee-reminders/send': 'capability: charge.campaign.send',
  'GET /api/v1/students/:id/dues-clearance': 'capability: fee.statement.view',
  'POST /api/v1/students/:id/dues-clearance/override': 'capability: certificate.issue',
  // Phase 4 slice 34 (contracts/slice-34.md §1): certificate.issue everywhere (the void adds the
  // principal gate in the service, R293); the student's list also with student.view, scoped.
  'GET /api/v1/certificates': 'capability: certificate.issue',
  'GET /api/v1/certificates/:id': 'capability: certificate.issue',
  'GET /api/v1/certificates/:id/print': 'capability: certificate.issue',
  'POST /api/v1/certificates/:id/reissue': 'capability: certificate.issue',
  'POST /api/v1/certificates/:id/void': 'capability: certificate.issue',
  'GET /api/v1/students/:id/certificates': 'capability: certificate.issue | student.view',
  'POST /api/v1/students/:id/certificates': 'capability: certificate.issue',
  // Phase 3 slice 23: expense readers, the recorder's writes, the approver's decisions (§3.1).
  'GET /api/v1/expenses': 'capability: expense.record | expense.approve | finance.report.view',
  'POST /api/v1/expenses': 'capability: expense.record',
  'GET /api/v1/expenses/:id': 'capability: expense.record | expense.approve | finance.report.view',
  'PATCH /api/v1/expenses/:id': 'capability: expense.record',
  'POST /api/v1/expenses/:id/approve': 'capability: expense.approve',
  'GET /api/v1/expenses/:id/receipt': 'capability: expense.record | expense.approve | finance.report.view',
  'PATCH /api/v1/expenses/:id/receipt': 'capability: expense.record',
  'GET /api/v1/expenses/:id/receipt/thumbnail': 'capability: expense.record | expense.approve | finance.report.view',
  'POST /api/v1/expenses/:id/reject': 'capability: expense.approve',
  'POST /api/v1/expenses/:id/void': 'capability: expense.record | expense.approve',
  // Phase 3 slice 26 (A18): the school's own platform bill.
  'GET /api/v1/school/billing-status': 'capability: school.settings.manage',
  'GET /api/v1/school/settings': 'capability: school.settings.manage',
  'PATCH /api/v1/school/settings': 'capability: school.settings.manage',
  'GET /api/v1/sections/:id': 'staff',
  'PATCH /api/v1/sections/:id': 'capability: section.manage',
  'POST /api/v1/sections/:id/archive': 'capability: section.manage',
  'GET /api/v1/sections/:id/diary-entries': 'capability: diary.write',
  'POST /api/v1/sections/:id/diary-entries': 'capability: diary.write',
  'GET /api/v1/sections/:id/register': 'capability: attendance.student.mark | attendance.student.view_all',
  'POST /api/v1/sections/:id/submit-register': 'capability: attendance.student.mark',
  'GET /api/v1/staff': 'capability: staff.view',
  'POST /api/v1/staff': 'capability: staff.create',
  'GET /api/v1/staff-attendance': 'capability: attendance.staff.manage',
  'POST /api/v1/staff-attendance/:id/amend': 'capability: attendance.staff.manage',
  'POST /api/v1/staff-attendance/submit': 'capability: attendance.staff.manage',
  'GET /api/v1/staff/:id': 'capability: staff.view',
  'PATCH /api/v1/staff/:id': 'capability: staff.update',
  'GET /api/v1/staff/:id/attendance': 'capability: staff.view',
  'GET /api/v1/staff/:id/leave-balance': 'capability: staff.view',
  'GET /api/v1/staff/:id/leave-requests': 'capability: staff.view',
  // Phase 3 slice 25 (§3.1): salary, advances, the monthly run and payslips.
  'GET /api/v1/staff/:id/salary-structure': 'capability: staff.contract.manage | payroll.view',
  'POST /api/v1/staff/:id/salary-structure': 'capability: staff.contract.manage',
  'GET /api/v1/salary-advances': 'capability: payroll.view',
  'POST /api/v1/salary-advances': 'capability: payroll.run',
  'GET /api/v1/salary-advances/:id': 'capability: payroll.view',
  'POST /api/v1/salary-advances/:id/write-off': 'capability: payroll.run',
  'GET /api/v1/payroll-runs': 'capability: payroll.view',
  'POST /api/v1/payroll-runs': 'capability: payroll.run',
  'GET /api/v1/payroll-runs/:id': 'capability: payroll.view',
  'GET /api/v1/payroll-runs/:id/payslips': 'capability: payroll.view',
  'POST /api/v1/payroll-runs/:id/payslips': 'capability: payroll.run',
  'POST /api/v1/payroll-runs/:id/recompute': 'capability: payroll.run',
  'POST /api/v1/payroll-runs/:id/finalise': 'capability: payroll.run',
  'GET /api/v1/payslips/:id': 'capability: payroll.view',
  'GET /api/v1/payslips/:id/print': 'capability: payroll.view',
  'POST /api/v1/payslips/:id/adjust': 'capability: payroll.run',
  'POST /api/v1/payslips/:id/mark-paid': 'capability: payroll.run',
  // Phase 3 slice 24: leave types and the approvers' queue.
  'GET /api/v1/leave-types': 'staff',
  'POST /api/v1/leave-types': 'capability: school.settings.manage',
  'POST /api/v1/leave-types/:id/archive': 'capability: school.settings.manage',
  'GET /api/v1/leave-requests': 'capability: staff.leave.approve',
  'POST /api/v1/leave-requests': 'capability: staff.leave.approve',
  'GET /api/v1/leave-requests/:id': 'capability: staff.leave.approve',
  'POST /api/v1/leave-requests/:id/approve': 'capability: staff.leave.approve',
  'POST /api/v1/leave-requests/:id/reject': 'capability: staff.leave.approve',
  'POST /api/v1/leave-requests/:id/end-early': 'capability: staff.leave.approve',
  'POST /api/v1/staff/:id/change-status': 'capability: staff.status.change',
  'POST /api/v1/staff/:id/issue-login': 'capability: user.account.manage',
  'GET /api/v1/staff/:id/teacher-assignments': 'capability: class.manage',
  'POST /api/v1/staff/:id/teacher-assignments': 'capability: class.manage',
  'GET /api/v1/students': 'capability: student.view',
  'GET /api/v1/students/:id': 'capability: student.view',
  'PATCH /api/v1/students/:id': 'capability: student.update',
  'GET /api/v1/students/:id/attendance': 'capability: student.view',
  'POST /api/v1/students/:id/change-status': 'capability: student.status.change',
  'GET /api/v1/students/:id/documents': 'capability: document.view',
  'POST /api/v1/students/:id/documents': 'capability: document.upload',
  'GET /api/v1/students/:id/enrolments': 'capability: student.view',
  'GET /api/v1/students/:id/guardian-links': 'capability: student.view',
  'POST /api/v1/students/:id/guardian-links': 'capability: guardian.manage',
  'POST /api/v1/students/:id/issue-login': 'capability: user.account.manage',
  'GET /api/v1/students/:id/photo': 'capability: document.view',
  'POST /api/v1/students/:id/readmit': 'capability: student.create',
  'GET /api/v1/students/:id/remarks': 'capability: student.view',
  'POST /api/v1/students/:id/remarks': 'capability: remark.write',
  'GET /api/v1/students/:id/status-changes': 'capability: student.view',
  'POST /api/v1/students/lookup': 'capability: student.create',
  'GET /api/v1/subjects': 'staff',
  'POST /api/v1/subjects': 'capability: subject.manage',
  'GET /api/v1/subjects/:id': 'staff',
  'PATCH /api/v1/subjects/:id': 'capability: subject.manage',
  'POST /api/v1/subjects/:id/archive': 'capability: subject.manage',
  'POST /api/v1/teacher-assignments/:id/end': 'capability: class.manage',
  'PATCH /api/v1/terms/:id': 'capability: assessment.define',
  'POST /api/v1/terms/:id/skip-class': 'capability: assessment.define',
  'POST /api/v1/terms/:id/set-up-exams': 'capability: assessment.define',
  'POST /api/v1/marks/:id/excuse': 'capability: result.approve',
  'POST /api/v1/terms/:id/unskip-class': 'capability: assessment.define',
  'POST /api/v1/uploads': 'capability: document.upload | diary.write | announcement.send.scope | announcement.send.school | expense.record',
  'POST /api/v1/user-roles/:id/remove': 'capability: role.manage',
  'GET /api/v1/users': 'capability: user.account.manage',
  'GET /api/v1/users/:id': 'capability: user.account.manage',
  'POST /api/v1/users/:id/disable': 'capability: user.account.manage',
  'POST /api/v1/users/:id/enable': 'capability: user.account.manage',
  'POST /api/v1/users/:id/grants': 'capability: role.manage',
  'GET /api/v1/users/:id/permissions': 'capability: role.manage',
  'POST /api/v1/users/:id/reset-password': 'capability: user.account.manage',
  'GET /api/v1/users/:id/roles': 'capability: user.account.manage | role.manage',
  'POST /api/v1/users/:id/roles': 'capability: role.manage',
  'POST /api/v1/users/:id/sign-out-everywhere': 'capability: user.account.manage',
  'GET /api/v1/webhooks/meta': 'webhook: meta',
  'POST /api/v1/webhooks/meta': 'webhook: meta',
  'POST /api/v1/webhooks/waha': 'webhook: waha',
};

/** 'METHOD path' keys ordered by path, then method, as the table is written. */
export const byPathThenMethod = (a: string, b: string): number => {
  const [ma = '', pa = ''] = a.split(' ');
  const [mb = '', pb = ''] = b.split(' ');
  return pa === pb ? ma.localeCompare(mb) : pa.localeCompare(pb);
};
