// R68 (slice 17): the reviewed table of every route's guard, read from the decorators of the real
// AppModule by test/core/routes.e2e-spec.ts. A route added, removed or re-guarded fails that test
// until this table is edited, so a changed guard is a visible diff in review, never a silent one:
// a capability list widened, a capacity swapped, a webhook provider or a platform level changed.
//
// Format: 'METHOD path': 'decorator[: argument]'. @RequireCapability lists its capabilities in
// declared order, ANY of which admits (contracts/slice-2.md §1); the row scope of a capability
// route is computed per request (R53, R79) and is not a decorator argument. @RequireCapacity names
// the capacity, @Webhook the provider, @PlatformSession the level. Print the actual table with
// PRINT_ROUTE_GUARDS=1 when editing; never paste it unread.

export const ROUTE_GUARDS: Record<string, string> = {
  'GET /api/v1/academic-years': 'staff',
  'POST /api/v1/academic-years': 'capability: academic_year.manage',
  'GET /api/v1/academic-years/:id': 'staff',
  'PATCH /api/v1/academic-years/:id': 'capability: academic_year.manage',
  'POST /api/v1/academic-years/:id/activate': 'capability: academic_year.manage',
  'POST /api/v1/academic-years/:id/close': 'capability: academic_year.manage',
  'POST /api/v1/admissions': 'capability: student.create',
  'GET /api/v1/announcements': 'capability: announcement.send.school | announcement.send.scope',
  'POST /api/v1/announcements': 'capability: announcement.send.school | announcement.send.scope',
  'GET /api/v1/announcements/:id': 'capability: announcement.send.school | announcement.send.scope',
  'PATCH /api/v1/announcements/:id': 'capability: announcement.send.school | announcement.send.scope',
  'GET /api/v1/announcements/:id/attachment': 'capability: announcement.send.school | announcement.send.scope',
  'POST /api/v1/announcements/:id/cancel': 'capability: announcement.send.school | announcement.send.scope',
  'GET /api/v1/announcements/:id/delivery': 'capability: announcement.send.school | announcement.send.scope',
  'POST /api/v1/announcements/:id/send': 'capability: announcement.send.school | announcement.send.scope',
  'GET /api/v1/announcements/:id/thumbnail': 'capability: announcement.send.school | announcement.send.scope',
  'POST /api/v1/announcements/preview-audience': 'capability: announcement.send.school | announcement.send.scope',
  'POST /api/v1/attendance-arrivals': 'capability: attendance.student.mark',
  'POST /api/v1/attendance-marks/:id/amend': 'capability: attendance.student.mark',
  'GET /api/v1/attendance-marks/:id/changes': 'capability: attendance.student.mark | attendance.student.view_all',
  'GET /api/v1/attendance-registers': 'capability: attendance.student.view_all | attendance.student.mark',
  'GET /api/v1/attendance-reports/absentees': 'capability: attendance.student.view_all',
  'GET /api/v1/attendance-reports/daily-summary': 'capability: attendance.student.view_all | attendance.student.mark',
  'GET /api/v1/attendance-reports/late': 'capability: attendance.student.view_all',
  'GET /api/v1/attendance-reports/percentage': 'capability: attendance.student.view_all',
  'POST /api/v1/auth/forgot-password': 'public',
  'POST /api/v1/auth/login': 'public',
  'POST /api/v1/auth/logout': 'authenticated-only',
  'POST /api/v1/auth/reset-password': 'public',
  'POST /api/v1/auth/verify-email': 'public',
  'GET /api/v1/calendar/teaching-days': 'staff',
  'GET /api/v1/classes': 'staff',
  'POST /api/v1/classes': 'capability: class.manage',
  'GET /api/v1/classes/:id': 'staff',
  'PATCH /api/v1/classes/:id': 'capability: class.manage',
  'POST /api/v1/classes/:id/archive': 'capability: class.manage',
  'POST /api/v1/classes/:id/copy-sections': 'capability: class.manage',
  'GET /api/v1/classes/:id/sections': 'staff',
  'POST /api/v1/classes/:id/sections': 'capability: section.manage',
  'GET /api/v1/custom-roles': 'capability: user.account.manage | role.manage',
  'POST /api/v1/custom-roles': 'capability: role.manage',
  'GET /api/v1/custom-roles/:id': 'capability: user.account.manage | role.manage',
  'PATCH /api/v1/custom-roles/:id': 'capability: role.manage',
  'POST /api/v1/custom-roles/:id/archive': 'capability: role.manage',
  'GET /api/v1/diary-entries/:id': 'capability: diary.write',
  'PATCH /api/v1/diary-entries/:id': 'capability: diary.write',
  'GET /api/v1/diary-entries/:id/attachment': 'capability: diary.write',
  'GET /api/v1/diary-entries/:id/thumbnail': 'capability: diary.write',
  'GET /api/v1/documents/:id/content': 'capability: document.view',
  'PATCH /api/v1/enrolments/:id': 'capability: enrolment.manage',
  'POST /api/v1/enrolments/:id/change-class': 'capability: enrolment.manage',
  'POST /api/v1/enrolments/:id/change-section': 'capability: enrolment.manage',
  'POST /api/v1/grants/:id/end': 'capability: role.manage',
  'PATCH /api/v1/guardian-links/:id': 'capability: guardian.manage',
  'POST /api/v1/guardian-links/:id/end': 'capability: guardian.manage',
  'GET /api/v1/guardians': 'capability: guardian.manage',
  'POST /api/v1/guardians': 'capability: guardian.manage',
  'GET /api/v1/guardians/:id': 'capability: guardian.manage',
  'PATCH /api/v1/guardians/:id': 'capability: guardian.manage',
  'POST /api/v1/guardians/:id/issue-login': 'capability: user.account.manage',
  'GET /api/v1/guardians/:id/students': 'capability: guardian.manage',
  'POST /api/v1/guardians/lookup': 'capability: student.create | guardian.manage',
  'GET /api/v1/health': 'public',
  'GET /api/v1/holidays': 'staff',
  'POST /api/v1/holidays': 'capability: holiday.manage',
  'GET /api/v1/holidays/:id': 'staff',
  'PATCH /api/v1/holidays/:id': 'capability: holiday.manage',
  'POST /api/v1/holidays/:id/cancel': 'capability: holiday.manage',
  'POST /api/v1/holidays/:id/publish': 'capability: holiday.manage',
  'GET /api/v1/me': 'authenticated-only',
  'GET /api/v1/me/calendar': 'authenticated-only',
  'POST /api/v1/me/change-email': 'authenticated-only',
  'POST /api/v1/me/change-password': 'authenticated-only',
  'GET /api/v1/me/children/:id/attendance': 'capacity: guardian',
  'GET /api/v1/me/children/:id/diary-entries': 'capacity: guardian',
  'GET /api/v1/me/children/:id/diary-entries/:entryId/attachment': 'capacity: guardian',
  'GET /api/v1/me/children/:id/diary-entries/:entryId/thumbnail': 'capacity: guardian',
  'GET /api/v1/me/children/:id/remarks': 'capacity: guardian',
  'POST /api/v1/me/devices': 'authenticated-only',
  'GET /api/v1/me/inbox': 'authenticated-only',
  'GET /api/v1/me/inbox/:id': 'authenticated-only',
  'GET /api/v1/me/inbox/:id/attachment': 'authenticated-only',
  'GET /api/v1/me/inbox/:id/thumbnail': 'authenticated-only',
  'POST /api/v1/me/sessions/revoke-others': 'authenticated-only',
  'GET /api/v1/me/staff/attendance': 'staff',
  'GET /api/v1/me/student/attendance': 'capacity: student',
  'GET /api/v1/me/student/diary-entries': 'capacity: student',
  'GET /api/v1/me/student/diary-entries/:entryId/attachment': 'capacity: student',
  'GET /api/v1/me/student/diary-entries/:entryId/thumbnail': 'capacity: student',
  'GET /api/v1/me/student/remarks': 'capacity: student',
  'POST /api/v1/messaging/test': 'capability: school.settings.manage',
  'GET /api/v1/messaging/usage': 'capability: school.settings.manage',
  'GET /api/v1/messaging/whatsapp': 'capability: school.settings.manage',
  'POST /api/v1/messaging/whatsapp/connect-cloud-api': 'capability: school.settings.manage',
  'POST /api/v1/messaging/whatsapp/disable': 'capability: school.settings.manage',
  'POST /api/v1/messaging/whatsapp/pair': 'capability: school.settings.manage',
  'POST /api/v1/platform/auth/change-password': 'platform-session: password-change',
  'POST /api/v1/platform/auth/login': 'public',
  'POST /api/v1/platform/auth/logout': 'platform-session: any',
  'POST /api/v1/platform/auth/totp/confirm': 'platform-session: any',
  'POST /api/v1/platform/auth/totp/enrol': 'platform-session: any',
  'GET /api/v1/platform/me': 'platform-session: any',
  'GET /api/v1/platform/messaging/health': 'platform-session: full',
  'GET /api/v1/platform/schools': 'platform-session: full',
  'POST /api/v1/platform/schools': 'platform-session: full',
  'GET /api/v1/platform/schools/:id': 'platform-session: full',
  'PATCH /api/v1/platform/schools/:id': 'platform-session: full',
  'POST /api/v1/platform/schools/:id/change-status': 'platform-session: full',
  'POST /api/v1/platform/schools/:id/issue-principal-login': 'platform-session: full',
  'GET /api/v1/platform/settings': 'platform-session: full',
  'PATCH /api/v1/platform/settings': 'platform-session: full',
  'POST /api/v1/remarks/:id/correct': 'capability: remark.write',
  // Phase 3 slice 18: finance readers (phase-3-financial.md §3.1, R234) and the setup writers.
  'GET /api/v1/fee-heads': 'capability: fee_head.manage | charge.create | fee.statement.view | payment.record',
  'POST /api/v1/fee-heads': 'capability: fee_head.manage',
  'GET /api/v1/fee-heads/:id': 'capability: fee_head.manage | charge.create | fee.statement.view | payment.record',
  'PATCH /api/v1/fee-heads/:id': 'capability: fee_head.manage',
  'POST /api/v1/fee-heads/:id/archive': 'capability: fee_head.manage',
  'GET /api/v1/fee-structures': 'capability: fee_head.manage | charge.create | fee.statement.view | payment.record',
  'POST /api/v1/fee-structures': 'capability: fee_head.manage',
  'POST /api/v1/fee-structures/copy': 'capability: fee_head.manage',
  'GET /api/v1/me/payment-accounts': 'capacity: guardian',
  'GET /api/v1/payment-accounts': 'capability: fee_head.manage | charge.create | fee.statement.view | payment.record',
  'POST /api/v1/payment-accounts': 'capability: school.settings.manage',
  'GET /api/v1/payment-accounts/:id': 'capability: fee_head.manage | charge.create | fee.statement.view | payment.record',
  'POST /api/v1/payment-accounts/:id/disable': 'capability: school.settings.manage',
  'GET /api/v1/school/settings': 'capability: school.settings.manage',
  'PATCH /api/v1/school/settings': 'capability: school.settings.manage',
  'GET /api/v1/sections/:id': 'staff',
  'PATCH /api/v1/sections/:id': 'capability: section.manage',
  'POST /api/v1/sections/:id/archive': 'capability: section.manage',
  'GET /api/v1/sections/:id/diary-entries': 'capability: diary.write',
  'POST /api/v1/sections/:id/diary-entries': 'capability: diary.write',
  'GET /api/v1/sections/:id/register': 'capability: attendance.student.mark | attendance.student.view_all',
  'POST /api/v1/sections/:id/submit-register': 'capability: attendance.student.mark',
  'GET /api/v1/staff': 'capability: staff.view',
  'POST /api/v1/staff': 'capability: staff.create',
  'GET /api/v1/staff-attendance': 'capability: attendance.staff.manage',
  'POST /api/v1/staff-attendance/:id/amend': 'capability: attendance.staff.manage',
  'POST /api/v1/staff-attendance/submit': 'capability: attendance.staff.manage',
  'GET /api/v1/staff/:id': 'capability: staff.view',
  'PATCH /api/v1/staff/:id': 'capability: staff.update',
  'GET /api/v1/staff/:id/attendance': 'capability: staff.view',
  'POST /api/v1/staff/:id/change-status': 'capability: staff.status.change',
  'POST /api/v1/staff/:id/issue-login': 'capability: user.account.manage',
  'GET /api/v1/staff/:id/teacher-assignments': 'capability: class.manage',
  'POST /api/v1/staff/:id/teacher-assignments': 'capability: class.manage',
  'GET /api/v1/students': 'capability: student.view',
  'GET /api/v1/students/:id': 'capability: student.view',
  'PATCH /api/v1/students/:id': 'capability: student.update',
  'GET /api/v1/students/:id/attendance': 'capability: student.view',
  'POST /api/v1/students/:id/change-status': 'capability: student.status.change',
  'GET /api/v1/students/:id/documents': 'capability: document.view',
  'POST /api/v1/students/:id/documents': 'capability: document.upload',
  'GET /api/v1/students/:id/enrolments': 'capability: student.view',
  'GET /api/v1/students/:id/guardian-links': 'capability: student.view',
  'POST /api/v1/students/:id/guardian-links': 'capability: guardian.manage',
  'POST /api/v1/students/:id/issue-login': 'capability: user.account.manage',
  'GET /api/v1/students/:id/photo': 'capability: document.view',
  'POST /api/v1/students/:id/readmit': 'capability: student.create',
  'GET /api/v1/students/:id/remarks': 'capability: student.view',
  'POST /api/v1/students/:id/remarks': 'capability: remark.write',
  'GET /api/v1/students/:id/status-changes': 'capability: student.view',
  'POST /api/v1/students/lookup': 'capability: student.create',
  'GET /api/v1/subjects': 'staff',
  'POST /api/v1/subjects': 'capability: subject.manage',
  'GET /api/v1/subjects/:id': 'staff',
  'PATCH /api/v1/subjects/:id': 'capability: subject.manage',
  'POST /api/v1/subjects/:id/archive': 'capability: subject.manage',
  'POST /api/v1/teacher-assignments/:id/end': 'capability: class.manage',
  'POST /api/v1/uploads': 'capability: document.upload | diary.write | announcement.send.scope | announcement.send.school',
  'POST /api/v1/user-roles/:id/remove': 'capability: role.manage',
  'GET /api/v1/users': 'capability: user.account.manage',
  'GET /api/v1/users/:id': 'capability: user.account.manage',
  'POST /api/v1/users/:id/disable': 'capability: user.account.manage',
  'POST /api/v1/users/:id/enable': 'capability: user.account.manage',
  'POST /api/v1/users/:id/grants': 'capability: role.manage',
  'GET /api/v1/users/:id/permissions': 'capability: role.manage',
  'POST /api/v1/users/:id/reset-password': 'capability: user.account.manage',
  'GET /api/v1/users/:id/roles': 'capability: user.account.manage | role.manage',
  'POST /api/v1/users/:id/roles': 'capability: role.manage',
  'POST /api/v1/users/:id/sign-out-everywhere': 'capability: user.account.manage',
  'GET /api/v1/webhooks/meta': 'webhook: meta',
  'POST /api/v1/webhooks/meta': 'webhook: meta',
  'POST /api/v1/webhooks/waha': 'webhook: waha',
};

/** 'METHOD path' keys ordered by path, then method, as the table is written. */
export const byPathThenMethod = (a: string, b: string): number => {
  const [ma = '', pa = ''] = a.split(' ');
  const [mb = '', pb = ''] = b.split(' ');
  return pa === pb ? ma.localeCompare(mb) : pa.localeCompare(pb);
};
