'use client';

import { formatRupees, newIdempotencyKey } from '@asms/shared';
import { zodResolver } from '@hookform/resolvers/zod';
import { keepPreviousData, useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { createColumnHelper } from '@tanstack/react-table';
import { PlusIcon } from 'lucide-react';
import { useMemo, useState } from 'react';
import { useForm, useWatch } from 'react-hook-form';
import { toast } from 'sonner';
import { z } from 'zod';
import { CheckboxField } from '@/components/checkbox-field';
import { ConfirmWithReasonDialog } from '@/components/confirm-with-reason-dialog';
import { DataTable, type DataTableFeatures, type RowAction, RowActions } from '@/components/data-table';
import { FormField, FormRootError, applyApiError } from '@/components/form-field';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { OPTIONS_LIMIT, unwrap } from '@/lib/api/client';
import { ApiError, toastApiError } from '@/lib/api/errors';
import {
  chargesApi,
  type CampaignAudience,
  type CampaignDto,
  type CampaignListQuery,
  type CampaignPreviewDto,
} from '@/lib/api/school-charges-contract';
import { feesApi } from '@/lib/api/school-fees-contract';
import { formatDate } from '@/lib/format';
import { useListPage } from '@/lib/hooks';
import { useClasses, useYears } from '../../academics/_lib/options';
import { CAMPAIGN_STATUS_LABELS, digitsOnly, feesKeys, rupeesSchema } from '../_lib/fees-ui';

const LIMIT = 25;

/**
 * Campaigns (slice 19, R184): a one-off fee (an exam, a trip) charged once to every student an
 * audience reaches, generated by a job, then told to each family.
 */
export function CampaignList() {
  const queryClient = useQueryClient();
  const [page, setPage] = useListPage([]);
  const [composing, setComposing] = useState(false);
  const [cancelling, setCancelling] = useState<CampaignDto | null>(null);
  const query: CampaignListQuery = { page, limit: LIMIT };
  const campaigns = useQuery({
    queryKey: [...feesKeys.campaigns, 'list', query],
    queryFn: () => unwrap(chargesApi.GET('/api/v1/charge-campaigns', { params: { query } })),
    placeholderData: keepPreviousData,
    refetchInterval: (q) => (q.state.data?.data.some((c) => c.status === 'generating') ? 5000 : false),
  });
  const refresh = () => void queryClient.invalidateQueries({ queryKey: feesKeys.all });

  const generate = useMutation({
    mutationFn: (c: CampaignDto) =>
      unwrap(chargesApi.POST('/api/v1/charge-campaigns/{id}/generate', { params: { path: { id: c.id } } })),
    onSuccess: () => {
      toast.success('Charging has started. Families are told when it finishes.');
      refresh();
    },
    onError: (error) => {
      toastApiError(error);
      refresh();
    },
  });
  const cancel = useMutation({
    mutationFn: ({ id, reason }: { id: string; reason: string }) =>
      unwrap(chargesApi.POST('/api/v1/charge-campaigns/{id}/cancel', { params: { path: { id } }, body: { reason } })),
    onSuccess: (c) => {
      toast.success(`${c.name} cancelled.`);
      refresh();
      setCancelling(null);
    },
    onError: (error) => {
      toastApiError(error);
      if (error instanceof ApiError && error.status === 409) setCancelling(null);
    },
  });

  const columns = useMemo(() => {
    const column = createColumnHelper<DataTableFeatures, CampaignDto>();
    return [
      column.accessor('name', {
        header: 'Campaign',
        cell: (info) => (
          <span className="flex flex-col">
            <span className="font-medium">{info.getValue()}</span>
            <span className="text-xs text-muted-foreground">{info.row.original.feeHeadName}</span>
          </span>
        ),
      }),
      column.accessor('amount', {
        header: () => <span className="block text-right">Amount</span>,
        cell: (info) => <span className="block text-right tabular-nums">{formatRupees(info.getValue())}</span>,
      }),
      column.accessor('dueOn', { header: 'Due', cell: (info) => formatDate(info.getValue()) }),
      column.accessor('status', {
        header: 'Status',
        cell: (info) => (
          <span className="flex flex-col gap-1">
            <Badge variant={info.getValue() === 'draft' ? 'default' : 'ghost'}>{CAMPAIGN_STATUS_LABELS[info.getValue()]}</Badge>
            {info.row.original.generatedCount !== null && (
              <span className="text-xs text-muted-foreground">{info.row.original.generatedCount} students charged</span>
            )}
          </span>
        ),
      }),
      column.display({
        id: 'actions',
        header: () => <span className="sr-only">Actions</span>,
        cell: (info) => {
          const c = info.row.original;
          const actions: RowAction[] = [];
          if (c.status === 'draft') actions.push({ label: 'Charge now', onSelect: () => generate.mutate(c) });
          if (c.status === 'draft' || c.status === 'generated') {
            actions.push({ label: 'Cancel', onSelect: () => setCancelling(c), destructive: true });
          }
          return <RowActions label={c.name} actions={actions} />;
        },
      }),
    ];
  }, [generate]);

  return (
    <>
      <div className="mb-4 flex justify-end">
        <Button onClick={() => setComposing(true)}>
          <PlusIcon />
          New campaign
        </Button>
      </div>
      <DataTable
        columns={columns}
        query={campaigns}
        getRowId={(row) => row.id}
        page={page}
        limit={LIMIT}
        onPageChange={setPage}
        emptyTitle="No campaigns yet"
        emptyDescription="A campaign charges a one-off fee, such as an exam or trip fee, to the students you choose."
      />
      <Dialog open={composing} onOpenChange={(open) => !open && setComposing(false)}>
        <DialogContent className="sm:max-w-xl">{composing && <CampaignForm onDone={() => setComposing(false)} />}</DialogContent>
      </Dialog>
      <ConfirmWithReasonDialog
        open={cancelling !== null}
        onOpenChange={(open) => !open && setCancelling(null)}
        title={`Cancel campaign: ${cancelling?.name ?? ''}`}
        description={
          cancelling?.status === 'generated'
            ? 'Charges already raised stay; void them one by one if they were wrong.'
            : 'The draft is kept as cancelled.'
        }
        confirmLabel="Cancel campaign"
        minLength={3}
        destructive
        pending={cancel.isPending}
        onConfirm={(reason) => cancelling && cancel.mutate({ id: cancelling.id, reason })}
      />
    </>
  );
}

const campaignSchema = z.object({
  name: z.string().trim().min(1, 'Give the campaign a name.').max(120),
  academicYearId: z.string().min(1, 'Pick a year.'),
  feeHeadId: z.string().min(1, 'Pick a fee head.'),
  amount: rupeesSchema.refine((v) => Number(v) >= 1, 'Enter an amount.'),
  dueOn: z.string().min(1, 'Pick a due date.'),
  applyConcessions: z.boolean(),
  everyone: z.boolean(),
});
type CampaignValues = z.infer<typeof campaignSchema>;

function CampaignForm({ onDone }: { onDone: () => void }) {
  const queryClient = useQueryClient();
  const [idempotencyKey, setIdempotencyKey] = useState(newIdempotencyKey);
  const [classIds, setClassIds] = useState<ReadonlySet<string>>(new Set());
  const [preview, setPreview] = useState<CampaignPreviewDto | null>(null);
  const years = useYears();
  const active = years.data?.data.find((y) => y.status === 'active');
  const form = useForm<CampaignValues>({
    resolver: zodResolver(campaignSchema),
    values: { name: '', academicYearId: active?.id ?? '', feeHeadId: '', amount: '', dueOn: '', applyConcessions: false, everyone: true },
    resetOptions: { keepDirtyValues: true },
  });
  const [yearId, everyone] = useWatch({ control: form.control, name: ['academicYearId', 'everyone'] });
  const classes = useClasses(yearId);
  const headsQuery = { status: 'active', limit: OPTIONS_LIMIT, sort: 'name' } as const;
  const heads = useQuery({
    queryKey: [...feesKeys.heads, 'options'],
    queryFn: () => unwrap(feesApi.GET('/api/v1/fee-heads', { params: { query: headsQuery } })),
  });
  const headOptions = [
    { value: '', label: 'Choose…' },
    ...(heads.data?.data ?? []).filter((h) => h.frequency === 'per_term' || h.frequency === 'ad_hoc').map((h) => ({ value: h.id, label: h.name })),
  ];
  const yearOptions = (years.data?.data ?? []).filter((y) => y.status !== 'closed').map((y) => ({ value: y.id, label: y.name }));

  const audiences = (): CampaignAudience[] =>
    everyone ? [{ kind: 'everyone' }] : [...classIds].map((targetId) => ({ kind: 'class', targetId }));

  const previewing = useMutation({
    mutationFn: (v: CampaignValues) =>
      unwrap(
        chargesApi.POST('/api/v1/charge-campaigns/preview-targets', {
          body: { academicYearId: v.academicYearId, feeHeadId: v.feeHeadId, amount: Number(v.amount), applyConcessions: v.applyConcessions, audiences: audiences() },
        }),
      ),
    onSuccess: setPreview,
    onError: (error) => applyApiError(form, error),
  });
  const save = useMutation({
    mutationFn: (v: CampaignValues) =>
      unwrap(
        chargesApi.POST('/api/v1/charge-campaigns', {
          params: { header: { 'Idempotency-Key': idempotencyKey } },
          body: {
            name: v.name,
            academicYearId: v.academicYearId,
            feeHeadId: v.feeHeadId,
            amount: Number(v.amount),
            dueOn: v.dueOn,
            applyConcessions: v.applyConcessions,
            audiences: audiences(),
          },
        }),
      ),
    onSuccess: (c) => {
      void queryClient.invalidateQueries({ queryKey: feesKeys.campaigns });
      toast.success(`${c.name} saved as a draft. Charge it from the list when ready.`);
      onDone();
    },
    onError: (error) => {
      if (error instanceof ApiError && error.code === 'IDEMPOTENCY_KEY_REUSED') setIdempotencyKey(newIdempotencyKey());
      applyApiError(form, error);
    },
  });
  const submit = (action: 'preview' | 'save') =>
    form.handleSubmit((v) => {
      if (!v.everyone && classIds.size === 0) return form.setError('root', { message: 'Choose every student or at least one class.' });
      if (action === 'preview') previewing.mutate(v);
      else save.mutate(v);
    });

  return (
    <form noValidate className="grid gap-4" onSubmit={submit('save')}>
      <DialogHeader>
        <DialogTitle>New campaign</DialogTitle>
        <DialogDescription>Saved as a draft. Nobody is charged until you choose “Charge now”.</DialogDescription>
      </DialogHeader>
      <FormRootError form={form} />
      <FormField control={form.control} name="name" label="Name" maxLength={120} autoFocus />
      <div className="grid gap-4 sm:grid-cols-2">
        <FormField control={form.control} name="academicYearId" label="Academic year" options={yearOptions} />
        <FormField control={form.control} name="feeHeadId" label="Fee head" options={headOptions} hint="A per-term or ad hoc head." />
        <FormField control={form.control} name="amount" label="Amount (Rs)" inputMode="numeric" maxLength={8} format={digitsOnly} />
        <FormField control={form.control} name="dueOn" label="Due on" type="date" />
      </div>
      <CheckboxField control={form.control} name="applyConcessions" label="Apply concessions" hint="Students with an approved concession on this head pay less." />
      <CheckboxField control={form.control} name="everyone" label="Every enrolled student" hint="Or choose classes below." />
      {!everyone && (
        <fieldset className="grid max-h-48 gap-1 overflow-y-auto rounded-md border p-3">
          <legend className="px-1 text-sm">Classes</legend>
          {(classes.data?.data ?? []).map((c) => (
            <label key={c.id} className="flex items-center gap-2 text-sm">
              <input
                type="checkbox"
                checked={classIds.has(c.id)}
                onChange={(e) => {
                  const next = new Set(classIds);
                  if (e.target.checked) next.add(c.id);
                  else next.delete(c.id);
                  setClassIds(next);
                }}
              />
              {c.name}
            </label>
          ))}
        </fieldset>
      )}
      {preview && (
        <p className="text-sm" role="status">
          {preview.targets.students} students will be charged.
          {preview.concessions.affected > 0 &&
            ` ${preview.concessions.affected} have a concession, ${formatRupees(preview.concessions.totalReduction)} in all.`}
        </p>
      )}
      <DialogFooter>
        <Button type="button" variant="outline" disabled={save.isPending} onClick={onDone}>
          Cancel
        </Button>
        <Button type="button" variant="outline" disabled={previewing.isPending} onClick={() => void submit('preview')()}>
          {previewing.isPending ? 'Counting…' : 'Preview'}
        </Button>
        <Button type="submit" disabled={save.isPending}>
          {save.isPending ? 'Saving…' : 'Save draft'}
        </Button>
      </DialogFooter>
    </form>
  );
}
