/**
 * Stable machine-readable error codes. A code never changes meaning once shipped;
 * messages may change. Slices add codes here as they need them.
 */
export const ErrorCode = {
  MALFORMED_REQUEST: 'MALFORMED_REQUEST',
  AUTH_REQUIRED: 'AUTH_REQUIRED',
  AUTH_FAILED: 'AUTH_FAILED',
  PERMISSION_DENIED: 'PERMISSION_DENIED',
  // Retired by Phase 2 slice 9 (contracts/slice-9.md §10: R80 lifted, a suspended school keeps
  // working). Kept because a code is never removed or reused; no route sends it after slice 9.
  SCHOOL_SUSPENDED: 'SCHOOL_SUSPENDED',
  ORIGIN_REJECTED: 'ORIGIN_REJECTED',
  NOT_FOUND: 'NOT_FOUND',
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  REFERENCE_NOT_FOUND: 'REFERENCE_NOT_FOUND',
  UNKNOWN_FIELD: 'UNKNOWN_FIELD',
  // Field-level: a value failed a shape rule (type, range, pattern). Used in details.fields only.
  INVALID_VALUE: 'INVALID_VALUE',
  PAYLOAD_TOO_LARGE: 'PAYLOAD_TOO_LARGE',
  UNSUPPORTED_MEDIA_TYPE: 'UNSUPPORTED_MEDIA_TYPE',
  RATE_LIMITED: 'RATE_LIMITED',
  SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  // slice 1: platform auth and schools
  PASSWORD_CHANGE_REQUIRED: 'PASSWORD_CHANGE_REQUIRED',
  TOTP_REQUIRED: 'TOTP_REQUIRED',
  TOTP_NOT_ENROLLED: 'TOTP_NOT_ENROLLED',
  TOTP_ALREADY_ENROLLED: 'TOTP_ALREADY_ENROLLED',
  TOTP_INVALID: 'TOTP_INVALID',
  CURRENT_PASSWORD_INCORRECT: 'CURRENT_PASSWORD_INCORRECT',
  SCHOOL_SHORT_CODE_TAKEN: 'SCHOOL_SHORT_CODE_TAKEN',
  SCHOOL_SHORT_CODE_IMMUTABLE: 'SCHOOL_SHORT_CODE_IMMUTABLE',
  SCHOOL_TERMINATED: 'SCHOOL_TERMINATED',
  ILLEGAL_STATUS_TRANSITION: 'ILLEGAL_STATUS_TRANSITION',
  // A write lost every retry to concurrent writes on the same row. The client reloads and retries.
  CONCURRENT_UPDATE: 'CONCURRENT_UPDATE',
  // slice 2: school auth, users, settings
  TOKEN_INVALID: 'TOKEN_INVALID',
  EMAIL_NOT_VERIFIED: 'EMAIL_NOT_VERIFIED',
  SELF_ACTION_FORBIDDEN: 'SELF_ACTION_FORBIDDEN',
  LAST_PRINCIPAL: 'LAST_PRINCIPAL',
  IDENTITY_NUMBER_MISSING: 'IDENTITY_NUMBER_MISSING',
  ACTIVE_PRINCIPAL_EXISTS: 'ACTIVE_PRINCIPAL_EXISTS',
  ALREADY_PRINCIPAL: 'ALREADY_PRINCIPAL',
  STAFF_NOT_ACTIVE: 'STAFF_NOT_ACTIVE',
  USER_DISABLED: 'USER_DISABLED',
  // slice 3: academic structure
  ACADEMIC_YEAR_NAME_TAKEN: 'ACADEMIC_YEAR_NAME_TAKEN',
  ACADEMIC_YEAR_CLOSED: 'ACADEMIC_YEAR_CLOSED',
  ACADEMIC_YEAR_HAS_ACTIVE_ENROLMENTS: 'ACADEMIC_YEAR_HAS_ACTIVE_ENROLMENTS',
  CLASS_NAME_TAKEN: 'CLASS_NAME_TAKEN',
  CLASS_YEAR_IMMUTABLE: 'CLASS_YEAR_IMMUTABLE',
  CLASS_ARCHIVED: 'CLASS_ARCHIVED',
  CLASS_HAS_ACTIVE_ENROLMENTS: 'CLASS_HAS_ACTIVE_ENROLMENTS',
  SECTION_NAME_TAKEN: 'SECTION_NAME_TAKEN',
  SECTION_ARCHIVED: 'SECTION_ARCHIVED',
  SECTION_IN_USE: 'SECTION_IN_USE',
  SUBJECT_NAME_TAKEN: 'SUBJECT_NAME_TAKEN',
  SUBJECT_CODE_TAKEN: 'SUBJECT_CODE_TAKEN',
  SUBJECT_ARCHIVED: 'SUBJECT_ARCHIVED',
  // slice 5: guardians
  GUARDIAN_CNIC_EXISTS: 'GUARDIAN_CNIC_EXISTS',
  GUARDIAN_CNIC_LOCKED: 'GUARDIAN_CNIC_LOCKED',
  GUARDIAN_MERGED: 'GUARDIAN_MERGED',
  GUARDIAN_CNIC_MISSING: 'GUARDIAN_CNIC_MISSING',
  GUARDIAN_NO_LOGIN_LINK: 'GUARDIAN_NO_LOGIN_LINK',
  GUARDIAN_IS_PRIMARY_CONTACT: 'GUARDIAN_IS_PRIMARY_CONTACT',
  LOGIN_ALREADY_EXISTS: 'LOGIN_ALREADY_EXISTS',
  // issue-principal-login onto an existing login without confirmLinkExisting: true (wave-A fix).
  LINK_EXISTING_LOGIN_UNCONFIRMED: 'LINK_EXISTING_LOGIN_UNCONFIRMED',
  // slice 4: staff, teacher assignments, roles
  STAFF_CNIC_EXISTS: 'STAFF_CNIC_EXISTS',
  STAFF_CNIC_LOCKED: 'STAFF_CNIC_LOCKED',
  USERNAME_IN_USE: 'USERNAME_IN_USE',
  CLASS_TEACHER_EXISTS: 'CLASS_TEACHER_EXISTS',
  ASSIGNMENT_EXISTS: 'ASSIGNMENT_EXISTS',
  ROLE_ALREADY_ASSIGNED: 'ROLE_ALREADY_ASSIGNED',
  // slice 6: students, enrolment, admission
  STUDENT_BFORM_EXISTS: 'STUDENT_BFORM_EXISTS',
  STUDENT_BFORM_LOCKED: 'STUDENT_BFORM_LOCKED',
  STUDENT_NOT_ACTIVE: 'STUDENT_NOT_ACTIVE',
  STUDENT_LOGIN_DISABLED: 'STUDENT_LOGIN_DISABLED',
  IDEMPOTENCY_KEY_REUSED: 'IDEMPOTENCY_KEY_REUSED',
  ADMISSION_POSSIBLE_DUPLICATE: 'ADMISSION_POSSIBLE_DUPLICATE',
  GUARDIAN_LINK_EXISTS: 'GUARDIAN_LINK_EXISTS',
  GUARDIAN_LINK_ENDED: 'GUARDIAN_LINK_ENDED',
  PRIMARY_CONTACT_REQUIRED: 'PRIMARY_CONTACT_REQUIRED',
  PRIMARY_CONTACT_NEEDS_PHONE: 'PRIMARY_CONTACT_NEEDS_PHONE',
  FEE_PAYER_REQUIRED: 'FEE_PAYER_REQUIRED',
  ENROLMENT_NOT_ACTIVE: 'ENROLMENT_NOT_ACTIVE',
  ROLL_NO_TAKEN: 'ROLL_NO_TAKEN',
  CLASS_IN_OTHER_YEAR: 'CLASS_IN_OTHER_YEAR',
  // slice 7: custom roles, grants
  CUSTOM_ROLE_KEY_TAKEN: 'CUSTOM_ROLE_KEY_TAKEN',
  CUSTOM_ROLE_ARCHIVED: 'CUSTOM_ROLE_ARCHIVED',
  CUSTOM_ROLE_IN_USE: 'CUSTOM_ROLE_IN_USE',
  GRANT_EXISTS: 'GRANT_EXISTS',
  // A grant or revoke aimed at a principal: principals are unrestricted peers (slice-7 §4.1).
  TARGET_IS_PRINCIPAL: 'TARGET_IS_PRINCIPAL',
  // Phase 2 (phase-2-daily-operations.md §6.1). The HTTP status each is sent with follows it.
  UPGRADE_REQUIRED: 'UPGRADE_REQUIRED', // 426, details.minimumVersion
  WEBHOOK_SIGNATURE_INVALID: 'WEBHOOK_SIGNATURE_INVALID', // 401, no details
  BEARER_SESSION_REQUIRED: 'BEARER_SESSION_REQUIRED', // 409
  CONTACT_PHONE_MISSING: 'CONTACT_PHONE_MISSING', // 409
  SMS_CAP_EXCEEDED: 'SMS_CAP_EXCEEDED', // 409, details { smsUnits, remaining, cap }
  SMS_TOO_LONG: 'SMS_TOO_LONG', // 409
  WHATSAPP_ALREADY_CONNECTED: 'WHATSAPP_ALREADY_CONNECTED', // 409
  WHATSAPP_NUMBER_MISSING: 'WHATSAPP_NUMBER_MISSING', // 409
  // contracts/slice-9.md §11
  WHATSAPP_PROVIDER_MISMATCH: 'WHATSAPP_PROVIDER_MISMATCH', // 409, details.provider
  WHATSAPP_VERIFICATION_FAILED: 'WHATSAPP_VERIFICATION_FAILED', // 409, details.reason
  HOLIDAY_DATES_TAKEN: 'HOLIDAY_DATES_TAKEN', // 409, details { holidayId }
  HOLIDAY_NOT_DRAFT: 'HOLIDAY_NOT_DRAFT', // 409
  NOT_A_TEACHING_DAY: 'NOT_A_TEACHING_DAY', // 409
  ATTENDANCE_LOCKED: 'ATTENDANCE_LOCKED', // 409
  AMENDMENT_REASON_REQUIRED: 'AMENDMENT_REASON_REQUIRED', // 409, details.amendments
  ROSTER_INCOMPLETE: 'ROSTER_INCOMPLETE', // 422, details.missing
  STALE_STATUS: 'STALE_STATUS', // 409
  ARRIVAL_NOT_ABSENT: 'ARRIVAL_NOT_ABSENT', // 409
  DIARY_ENTRY_EXISTS: 'DIARY_ENTRY_EXISTS', // 409, details { entryId }
  DIARY_ENTRY_LOCKED: 'DIARY_ENTRY_LOCKED', // 409
  SUBJECT_NOT_ASSIGNED: 'SUBJECT_NOT_ASSIGNED', // 409
  REMARK_SUPERSEDED: 'REMARK_SUPERSEDED', // 409, details { supersededById }
  ANNOUNCEMENT_SENT: 'ANNOUNCEMENT_SENT', // 409
  ANNOUNCEMENT_CANCELLED: 'ANNOUNCEMENT_CANCELLED', // 409
  ANNOUNCEMENT_NO_RECIPIENTS: 'ANNOUNCEMENT_NO_RECIPIENTS', // 409
  // slice 10 (contracts/slice-10.md §10)
  CAPABILITY_NOT_HELD: 'CAPABILITY_NOT_HELD', // 409, details.capability: the target lacks it
  ATTENDANCE_RECORDED_AFTER: 'ATTENDANCE_RECORDED_AFTER', // 409, details.lastRecordedOn
  // Phase 3 (phase-3-financial.md §5.1). 409 unless stated.
  FEE_HEAD_NAME_TAKEN: 'FEE_HEAD_NAME_TAKEN', // details.feeHeadId
  FEE_HEAD_CATEGORY_TAKEN: 'FEE_HEAD_CATEGORY_TAKEN', // details.feeHeadId
  FEE_HEAD_ARCHIVED: 'FEE_HEAD_ARCHIVED', // details.feeHeadId
  FEE_STRUCTURE_EXISTS: 'FEE_STRUCTURE_EXISTS', // details.structureId
  FEE_STRUCTURE_NOT_LATER: 'FEE_STRUCTURE_NOT_LATER', // details.latestEffectiveFrom
  FEE_STRUCTURE_MISSING: 'FEE_STRUCTURE_MISSING', // details { classId, feeHeadId }
  CONCESSION_EXISTS: 'CONCESSION_EXISTS',
  CONCESSION_NOT_PENDING: 'CONCESSION_NOT_PENDING',
  CONCESSION_HEAD_NOT_ELIGIBLE: 'CONCESSION_HEAD_NOT_ELIGIBLE',
  CHARGE_NOT_OPEN: 'CHARGE_NOT_OPEN',
  CHARGE_HAS_ALLOCATIONS: 'CHARGE_HAS_ALLOCATIONS',
  CHARGE_NOT_LATE_FEE: 'CHARGE_NOT_LATE_FEE',
  CHARGE_RUN_IN_PROGRESS: 'CHARGE_RUN_IN_PROGRESS', // details.runId
  MONTH_NOT_GENERATABLE: 'MONTH_NOT_GENERATABLE', // details.reason: future | outside_year | year_closed
  CAMPAIGN_NOT_DRAFT: 'CAMPAIGN_NOT_DRAFT',
  CAMPAIGN_NO_TARGETS: 'CAMPAIGN_NO_TARGETS',
  PAYMENT_SPANS_YEARS: 'PAYMENT_SPANS_YEARS',
  PAYMENT_NOTHING_DUE: 'PAYMENT_NOTHING_DUE',
  PAYMENT_VOIDED: 'PAYMENT_VOIDED',
  PAYMENT_IN_CUSTODY: 'PAYMENT_IN_CUSTODY', // inside an open handover
  PAYMENT_HAS_REFUND: 'PAYMENT_HAS_REFUND', // a refund or a carry-forward exists
  REFUND_EXCEEDS_UNALLOCATED: 'REFUND_EXCEEDS_UNALLOCATED',
  NOTHING_TO_CARRY_FORWARD: 'NOTHING_TO_CARRY_FORWARD',
  HANDOVER_OPEN: 'HANDOVER_OPEN',
  HANDOVER_NOTHING_TO_HAND_OVER: 'HANDOVER_NOTHING_TO_HAND_OVER',
  HANDOVER_NOT_OPEN: 'HANDOVER_NOT_OPEN',
  HANDOVER_NOT_CONFIRMED: 'HANDOVER_NOT_CONFIRMED',
  HANDOVER_NO_SHORTFALL: 'HANDOVER_NO_SHORTFALL',
  CLAIMS_NOT_ACCEPTED: 'CLAIMS_NOT_ACCEPTED',
  CLAIM_NOT_PENDING: 'CLAIM_NOT_PENDING',
  CLAIM_LIMIT_REACHED: 'CLAIM_LIMIT_REACHED',
  CLAIM_IMAGE_MISSING: 'CLAIM_IMAGE_MISSING',
  CLAIM_IMAGE_EXISTS: 'CLAIM_IMAGE_EXISTS',
  EXPENSE_NOT_PENDING: 'EXPENSE_NOT_PENDING',
  EXPENSE_NOT_OPEN: 'EXPENSE_NOT_OPEN',
  EXPENSE_RECEIPT_EXISTS: 'EXPENSE_RECEIPT_EXISTS',
  LEAVE_OVERLAPS: 'LEAVE_OVERLAPS',
  LEAVE_BALANCE_EXCEEDED: 'LEAVE_BALANCE_EXCEEDED', // details.balance
  LEAVE_NOT_PENDING: 'LEAVE_NOT_PENDING',
  LEAVE_STARTED: 'LEAVE_STARTED',
  LEAVE_TYPE_ARCHIVED: 'LEAVE_TYPE_ARCHIVED',
  LEAVE_TYPE_NAME_TAKEN: 'LEAVE_TYPE_NAME_TAKEN',
  SALARY_STRUCTURE_MISSING: 'SALARY_STRUCTURE_MISSING',
  SALARY_STRUCTURE_IN_USE: 'SALARY_STRUCTURE_IN_USE',
  ADVANCE_NOT_OPEN: 'ADVANCE_NOT_OPEN',
  PAYROLL_RUN_EXISTS: 'PAYROLL_RUN_EXISTS',
  PAYROLL_RUN_FINALISED: 'PAYROLL_RUN_FINALISED',
  PAYROLL_RUN_NOT_DRAFT: 'PAYROLL_RUN_NOT_DRAFT',
  PAYSLIP_PAID: 'PAYSLIP_PAID',
  PLAN_BAND_OVERLAPS: 'PLAN_BAND_OVERLAPS',
  PLAN_ARCHIVED: 'PLAN_ARCHIVED',
  PLAN_IN_USE: 'PLAN_IN_USE',
  INVOICE_NOT_ISSUED: 'INVOICE_NOT_ISSUED',
  // Phase 4 (phase-4-academic.md §5.1). 409 unless stated.
  TERM_OVERLAPS: 'TERM_OVERLAPS', // 409, details.termId
  TERM_OUTSIDE_YEAR: 'TERM_OUTSIDE_YEAR', // 409, details.termId (null on create)
  TERM_IN_USE: 'TERM_IN_USE', // 409, details.termId
  TERM_NAME_TAKEN: 'TERM_NAME_TAKEN', // 409, details.field = name (contracts/slice-29.md)
  RESULT_SETTINGS_LOCKED: 'RESULT_SETTINGS_LOCKED', // 409, details.academicYearId
  CLASS_SUBJECT_IN_USE: 'CLASS_SUBJECT_IN_USE', // 409, details.classSubjectId
  CLASS_SUBJECTS_FROZEN: 'CLASS_SUBJECTS_FROZEN', // 409, details.classId
  EXAM_NOT_SET_UP: 'EXAM_NOT_SET_UP', // 409, details { classSubjectId, sectionId, termId }
  ASSESSMENT_LOCKED: 'ASSESSMENT_LOCKED', // 409, details.assessmentId
  ASSESSMENT_OUTSIDE_TERM: 'ASSESSMENT_OUTSIDE_TERM', // 409, details.assessmentId
  ASSESSMENT_VOIDED: 'ASSESSMENT_VOIDED', // 409, details.assessmentId
  ASSESSMENT_HAS_MARKS: 'ASSESSMENT_HAS_MARKS', // 409, details.assessmentId
  MARK_EXCEEDS_MAX: 'MARK_EXCEEDS_MAX', // 409, details { enrolmentId, max } (the whole request)
  MARKS_INCOMPLETE: 'MARKS_INCOMPLETE', // 409, details.missing [{ enrolmentId, assessmentId }] (≤ 100)
  RESULT_SHEET_NOT_DRAFT: 'RESULT_SHEET_NOT_DRAFT', // 409, details.sheetId
  RESULT_SHEET_NOT_SUBMITTED: 'RESULT_SHEET_NOT_SUBMITTED', // 409, details.sheetId
  RESULT_SHEET_NOT_APPROVED: 'RESULT_SHEET_NOT_APPROVED', // 409, details.sheetId
  RESULT_SHEET_PUBLISHED: 'RESULT_SHEET_PUBLISHED', // 409, details.sheetId
  RESULT_SHEET_VERSION_OPEN: 'RESULT_SHEET_VERSION_OPEN', // 409, details.sheetId
  RESULT_SHEET_TERMS_UNPUBLISHED: 'RESULT_SHEET_TERMS_UNPUBLISHED', // 409, details.missingTermIds
  MARK_CORRECTION_NOT_PENDING: 'MARK_CORRECTION_NOT_PENDING', // 409, details.markId
  MARK_CORRECTION_SHEET_NOT_PUBLISHED: 'MARK_CORRECTION_SHEET_NOT_PUBLISHED', // 409, details.markId
  CERTIFICATE_DUES_BLOCK: 'CERTIFICATE_DUES_BLOCK', // 409, details.outstanding
  CERTIFICATE_STUDENT_NOT_LEFT: 'CERTIFICATE_STUDENT_NOT_LEFT', // 409, details.studentId
  CERTIFICATE_VOIDED: 'CERTIFICATE_VOIDED', // 409, details.certificateId
  CERTIFICATE_NO_RESULT: 'CERTIFICATE_NO_RESULT', // 409, details.certificateId
  PROMOTION_FINAL_NOT_APPROVED: 'PROMOTION_FINAL_NOT_APPROVED', // 409, details.sectionId
  PROMOTION_SHEET_OPEN: 'PROMOTION_SHEET_OPEN', // 409, details.sheetId
  PROMOTION_SHEET_NOT_OPEN: 'PROMOTION_SHEET_NOT_OPEN', // 409, details.sheetId
  PROMOTION_INCOMPLETE: 'PROMOTION_INCOMPLETE', // 409, details.enrolmentIds | details.sections
  PROMOTION_RESULT_SUPERSEDED: 'PROMOTION_RESULT_SUPERSEDED', // 409, details.enrolmentIds
  PROMOTION_TARGET_INVALID: 'PROMOTION_TARGET_INVALID', // 409, details.reason: other_year | archived | no_target
  // Rule 24 (R225): role.manage and user.account.manage are inert on a default password. 403.
  DEFAULT_PASSWORD_BLOCKS_ACTION: 'DEFAULT_PASSWORD_BLOCKS_ACTION',
  // Client-side only: the web app's label for a failed response whose body was not the error
  // envelope (a proxy page, say). The API never sends it.
  UNEXPECTED_RESPONSE: 'UNEXPECTED_RESPONSE',
} as const;

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];
