/**
 * Stable machine-readable error codes. A code never changes meaning once shipped;
 * messages may change. Slices add codes here as they need them.
 */
export const ErrorCode = {
  MALFORMED_REQUEST: 'MALFORMED_REQUEST',
  AUTH_REQUIRED: 'AUTH_REQUIRED',
  AUTH_FAILED: 'AUTH_FAILED',
  PERMISSION_DENIED: 'PERMISSION_DENIED',
  SCHOOL_SUSPENDED: 'SCHOOL_SUSPENDED',
  ORIGIN_REJECTED: 'ORIGIN_REJECTED',
  NOT_FOUND: 'NOT_FOUND',
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  REFERENCE_NOT_FOUND: 'REFERENCE_NOT_FOUND',
  UNKNOWN_FIELD: 'UNKNOWN_FIELD',
  PAYLOAD_TOO_LARGE: 'PAYLOAD_TOO_LARGE',
  UNSUPPORTED_MEDIA_TYPE: 'UNSUPPORTED_MEDIA_TYPE',
  RATE_LIMITED: 'RATE_LIMITED',
  SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
} as const;

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];
